package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA



/**
 * DespesasPagamentoId generated by hbm2java
 */
public class DespesasPagamentoId  implements java.io.Serializable {


     private int formaPagamentoCodigo;
     private int despesasCodigo;

    public DespesasPagamentoId() {
    }

    public DespesasPagamentoId(int formaPagamentoCodigo, int despesasCodigo) {
       this.formaPagamentoCodigo = formaPagamentoCodigo;
       this.despesasCodigo = despesasCodigo;
    }
   
    public int getFormaPagamentoCodigo() {
        return this.formaPagamentoCodigo;
    }
    
    public void setFormaPagamentoCodigo(int formaPagamentoCodigo) {
        this.formaPagamentoCodigo = formaPagamentoCodigo;
    }
    public int getDespesasCodigo() {
        return this.despesasCodigo;
    }
    
    public void setDespesasCodigo(int despesasCodigo) {
        this.despesasCodigo = despesasCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DespesasPagamentoId) ) return false;
		 DespesasPagamentoId castOther = ( DespesasPagamentoId ) other; 
         
		 return (this.getFormaPagamentoCodigo()==castOther.getFormaPagamentoCodigo())
 && (this.getDespesasCodigo()==castOther.getDespesasCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFormaPagamentoCodigo();
         result = 37 * result + this.getDespesasCodigo();
         return result;
   }   


}


