package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Despesas generated by hbm2java
 */
public class Despesas  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private Date dataDesp;
     private Date dataPag;
     private Integer parcelas;
     private Integer parcela;
     private Float valorParcela;
     private Float valor;
     private Float valorRestante;
     private String status;
     private String obs;
     private int codOrindo;
     private int codUsuario;
     private Date datAlteracao;
     private Integer pago;
     private Date dataPagamento;
     private Set despesasPagamentos = new HashSet(0);

    public Despesas() {
    }

	
    public Despesas(int codOrindo, int codUsuario) {
        this.codOrindo = codOrindo;
        this.codUsuario = codUsuario;
    }
    public Despesas(String descricao, Date dataDesp, Date dataPag, Integer parcelas, Integer parcela, Float valorParcela, Float valor, Float valorRestante, String status, String obs, int codOrindo, int codUsuario, Date datAlteracao, Integer pago, Date dataPagamento, Set despesasPagamentos) {
       this.descricao = descricao;
       this.dataDesp = dataDesp;
       this.dataPag = dataPag;
       this.parcelas = parcelas;
       this.parcela = parcela;
       this.valorParcela = valorParcela;
       this.valor = valor;
       this.valorRestante = valorRestante;
       this.status = status;
       this.obs = obs;
       this.codOrindo = codOrindo;
       this.codUsuario = codUsuario;
       this.datAlteracao = datAlteracao;
       this.pago = pago;
       this.dataPagamento = dataPagamento;
       this.despesasPagamentos = despesasPagamentos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataDesp() {
        return this.dataDesp;
    }
    
    public void setDataDesp(Date dataDesp) {
        this.dataDesp = dataDesp;
    }
    public Date getDataPag() {
        return this.dataPag;
    }
    
    public void setDataPag(Date dataPag) {
        this.dataPag = dataPag;
    }
    public Integer getParcelas() {
        return this.parcelas;
    }
    
    public void setParcelas(Integer parcelas) {
        this.parcelas = parcelas;
    }
    public Integer getParcela() {
        return this.parcela;
    }
    
    public void setParcela(Integer parcela) {
        this.parcela = parcela;
    }
    public Float getValorParcela() {
        return this.valorParcela;
    }
    
    public void setValorParcela(Float valorParcela) {
        this.valorParcela = valorParcela;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Float getValorRestante() {
        return this.valorRestante;
    }
    
    public void setValorRestante(Float valorRestante) {
        this.valorRestante = valorRestante;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public int getCodOrindo() {
        return this.codOrindo;
    }
    
    public void setCodOrindo(int codOrindo) {
        this.codOrindo = codOrindo;
    }
    public int getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(int codUsuario) {
        this.codUsuario = codUsuario;
    }
    public Date getDatAlteracao() {
        return this.datAlteracao;
    }
    
    public void setDatAlteracao(Date datAlteracao) {
        this.datAlteracao = datAlteracao;
    }
    public Integer getPago() {
        return this.pago;
    }
    
    public void setPago(Integer pago) {
        this.pago = pago;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public Set getDespesasPagamentos() {
        return this.despesasPagamentos;
    }
    
    public void setDespesasPagamentos(Set despesasPagamentos) {
        this.despesasPagamentos = despesasPagamentos;
    }




}


