package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FormaPagamento generated by hbm2java
 */
public class FormaPagamento  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private Date dataCadastro;
     private Date dataAlteracao;
     private Set despesasPagamentos = new HashSet(0);

    public FormaPagamento() {
    }

    public FormaPagamento(String nome, Date dataCadastro, Date dataAlteracao, Set despesasPagamentos) {
       this.nome = nome;
       this.dataCadastro = dataCadastro;
       this.dataAlteracao = dataAlteracao;
       this.despesasPagamentos = despesasPagamentos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }
    public Set getDespesasPagamentos() {
        return this.despesasPagamentos;
    }
    
    public void setDespesasPagamentos(Set despesasPagamentos) {
        this.despesasPagamentos = despesasPagamentos;
    }




}


