package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Oriundo generated by hbm2java
 */
public class Oriundo  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private Date dataCadastro;
     private Integer diaFechamento;
     private Integer diaPag;

    public Oriundo() {
    }

    public Oriundo(String descricao, Date dataCadastro, Integer diaFechamento, Integer diaPag) {
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.diaFechamento = diaFechamento;
       this.diaPag = diaPag;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Integer getDiaFechamento() {
        return this.diaFechamento;
    }
    
    public void setDiaFechamento(Integer diaFechamento) {
        this.diaFechamento = diaFechamento;
    }
    public Integer getDiaPag() {
        return this.diaPag;
    }
    
    public void setDiaPag(Integer diaPag) {
        this.diaPag = diaPag;
    }




}


