package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TicketLancamento generated by hbm2java
 */
public class TicketLancamento  implements java.io.Serializable {


     private Integer ITicketLancamento;
     private int tipo;
     private int ITicketCard;
     private int IInstituicao;
     private Double valor;
     private Date dataLancamento;
     private Date dataAlteracao;
     private Double saldoAnterior;
     private Integer validado;
     private Integer ILastLancamento;
     private Integer mesRef;
     private Integer anoRef;

    public TicketLancamento() {
    }

	
    public TicketLancamento(int tipo, int ITicketCard, int IInstituicao) {
        this.tipo = tipo;
        this.ITicketCard = ITicketCard;
        this.IInstituicao = IInstituicao;
    }
    public TicketLancamento(int tipo, int ITicketCard, int IInstituicao, Double valor, Date dataLancamento, Date dataAlteracao, Double saldoAnterior, Integer validado, Integer ILastLancamento, Integer mesRef, Integer anoRef) {
       this.tipo = tipo;
       this.ITicketCard = ITicketCard;
       this.IInstituicao = IInstituicao;
       this.valor = valor;
       this.dataLancamento = dataLancamento;
       this.dataAlteracao = dataAlteracao;
       this.saldoAnterior = saldoAnterior;
       this.validado = validado;
       this.ILastLancamento = ILastLancamento;
       this.mesRef = mesRef;
       this.anoRef = anoRef;
    }
   
    public Integer getITicketLancamento() {
        return this.ITicketLancamento;
    }
    
    public void setITicketLancamento(Integer ITicketLancamento) {
        this.ITicketLancamento = ITicketLancamento;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public int getITicketCard() {
        return this.ITicketCard;
    }
    
    public void setITicketCard(int ITicketCard) {
        this.ITicketCard = ITicketCard;
    }
    public int getIInstituicao() {
        return this.IInstituicao;
    }
    
    public void setIInstituicao(int IInstituicao) {
        this.IInstituicao = IInstituicao;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Date getDataLancamento() {
        return this.dataLancamento;
    }
    
    public void setDataLancamento(Date dataLancamento) {
        this.dataLancamento = dataLancamento;
    }
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }
    public Double getSaldoAnterior() {
        return this.saldoAnterior;
    }
    
    public void setSaldoAnterior(Double saldoAnterior) {
        this.saldoAnterior = saldoAnterior;
    }
    public Integer getValidado() {
        return this.validado;
    }
    
    public void setValidado(Integer validado) {
        this.validado = validado;
    }
    public Integer getILastLancamento() {
        return this.ILastLancamento;
    }
    
    public void setILastLancamento(Integer ILastLancamento) {
        this.ILastLancamento = ILastLancamento;
    }
    public Integer getMesRef() {
        return this.mesRef;
    }
    
    public void setMesRef(Integer mesRef) {
        this.mesRef = mesRef;
    }
    public Integer getAnoRef() {
        return this.anoRef;
    }
    
    public void setAnoRef(Integer anoRef) {
        this.anoRef = anoRef;
    }




}


