package com.projeto.despesa.hibernate;
// Generated 01/07/2013 15:09:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TicketTipo generated by hbm2java
 */
public class TicketTipo  implements java.io.Serializable {


     private Integer ITicketTipo;
     private String descricao;
     private Date dataCadastro;
     private Date dataAlteracao;

    public TicketTipo() {
    }

    public TicketTipo(String descricao, Date dataCadastro, Date dataAlteracao) {
       this.descricao = descricao;
       this.dataCadastro = dataCadastro;
       this.dataAlteracao = dataAlteracao;
    }
   
    public Integer getITicketTipo() {
        return this.ITicketTipo;
    }
    
    public void setITicketTipo(Integer ITicketTipo) {
        this.ITicketTipo = ITicketTipo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataAlteracao() {
        return this.dataAlteracao;
    }
    
    public void setDataAlteracao(Date dataAlteracao) {
        this.dataAlteracao = dataAlteracao;
    }




}


