/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projeto.despesa.form;

/**
 *
 * @author uhitlei.barbosa
 */
public class PainelButons extends javax.swing.JPanel {

    /**
     * Creates new form PainelButonsAlteracao
     */
    public PainelButons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Cancel.png"))); // NOI18N
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setEnabled(false);

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Sign-Shutdown-icon.png"))); // NOI18N
        btFechar.setToolTipText("Fechar");

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Delete-icon.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setEnabled(false);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Edit-Text-icon.png"))); // NOI18N
        btAlterar.setToolTipText("Alterar");
        btAlterar.setEnabled(false);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16check.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.setEnabled(false);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16_add_plus_icon.png"))); // NOI18N
        btNovo.setToolTipText("Novo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar)
                    .addComponent(btCancelar)
                    .addComponent(btFechar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAlterar;
    public javax.swing.JButton btCancelar;
    public javax.swing.JButton btExcluir;
    public javax.swing.JButton btFechar;
    public javax.swing.JButton btNovo;
    public javax.swing.JButton btSalvar;
    // End of variables declaration//GEN-END:variables
}
