/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * painelAvanceBack.java
 *
 * Created on 15/05/2012, 22:38:32
 */
package com.projeto.despesa.form;

/**
 *
 * @author WILL
 */
public class painelAvanceBack extends javax.swing.JPanel {

    /** Creates new form painelAvanceBack */
    public painelAvanceBack() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAvanceUm = new javax.swing.JButton();
        btAvanceAll = new javax.swing.JButton();
        btBackAll = new javax.swing.JButton();
        btBackUm = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(null);

        btAvanceUm.setText(">");
        add(btAvanceUm);
        btAvanceUm.setBounds(90, 0, 41, 14);

        btAvanceAll.setText(">>");
        add(btAvanceAll);
        btAvanceAll.setBounds(130, 0, 49, 14);

        btBackAll.setText("<<");
        add(btBackAll);
        btBackAll.setBounds(0, 0, 49, 14);

        btBackUm.setText("<");
        add(btBackUm);
        btBackUm.setBounds(50, 0, 41, 14);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAvanceAll;
    public javax.swing.JButton btAvanceUm;
    public javax.swing.JButton btBackAll;
    public javax.swing.JButton btBackUm;
    // End of variables declaration//GEN-END:variables
}
