/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projeto.despesa.form;

/**
 *
 * @author uhitlei.barbosa
 */
public class PainelButonsAlteracao extends javax.swing.JPanel {

    /**
     * Creates new form PainelButons
     */
    public PainelButonsAlteracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btProcurar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Cancel.png"))); // NOI18N
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setEnabled(false);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16check.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.setEnabled(false);

        btProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16search.png"))); // NOI18N
        btProcurar.setToolTipText("Novo");

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Edit-Text-icon.png"))); // NOI18N
        btAlterar.setToolTipText("Alterar");
        btAlterar.setEnabled(false);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Delete-icon.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btExcluir)
            .addComponent(btAlterar)
            .addComponent(btSalvar)
            .addComponent(btCancelar)
            .addComponent(btProcurar)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAlterar;
    public javax.swing.JButton btCancelar;
    public javax.swing.JButton btExcluir;
    public javax.swing.JButton btProcurar;
    public javax.swing.JButton btSalvar;
    // End of variables declaration//GEN-END:variables
}
