/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projeto.despesa.form;

import com.projeto.despesa.utilitarios.FormatarCampo;
import javax.swing.JFormattedTextField;

/**
 *
 * @author uhitlei.barbosa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    btAddDespesas = new javax.swing.JButton();
    btPagamento = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    painelTabelaDespesas = new com.projeto.despesa.form.PainelTabela();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cbMes = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    cbOrigenPag = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    tfAno = new JFormattedTextField(new FormatarCampo().getIntAno());
    jLabel4 = new javax.swing.JLabel();
    lbValor = new javax.swing.JLabel();
    btAtualizaTable = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    mnuArquivo = new javax.swing.JMenu();
    mnuNovo = new javax.swing.JMenu();
    mnuIDespesasNovo = new javax.swing.JMenuItem();
    mnuIOrigemNovo = new javax.swing.JMenuItem();
    mnuEditar = new javax.swing.JMenu();
    mnuIDespesasEditar = new javax.swing.JMenuItem();
    mnuIOrigemEditar = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Despesas Pessoais");
    setResizable(false);
    setState(1);

    jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jToolBar1.setRollover(true);

    btAddDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/conta16.png"))); // NOI18N
    btAddDespesas.setToolTipText("Despesas");
    btAddDespesas.setFocusable(false);
    btAddDespesas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    btAddDespesas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btAddDespesas);

    btPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/cost-management16.gif"))); // NOI18N
    btPagamento.setToolTipText("Pangamento");
    btPagamento.setFocusable(false);
    btPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btPagamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(btPagamento);
    jToolBar1.add(jSeparator1);

    painelTabelaDespesas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLabel1.setText("Mes:");

    cbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

    jLabel3.setText("Origem pag.");

    cbOrigenPag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel2.setText("Ano: ");

    tfAno.setText("2012");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(51, 51, 255));
    jLabel4.setText("Valor Mês:");

    lbValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    lbValor.setForeground(new java.awt.Color(51, 51, 255));
    lbValor.setText("0");

    btAtualizaTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projeto/despesa/images/16Refresh.png"))); // NOI18N
    btAtualizaTable.setBorderPainted(false);
    btAtualizaTable.setMaximumSize(new java.awt.Dimension(16, 16));
    btAtualizaTable.setMinimumSize(new java.awt.Dimension(16, 16));
    btAtualizaTable.setOpaque(false);
    btAtualizaTable.setPreferredSize(new java.awt.Dimension(20, 20));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(69, 69, 69)
            .addComponent(jLabel2)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel3)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(cbOrigenPag, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btAtualizaTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(173, 173, 173)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(102, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(12, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btAtualizaTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(cbOrigenPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbValor)
              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap())
    );

    mnuArquivo.setText("Arquivo");

    mnuNovo.setText("Novo");

    mnuIDespesasNovo.setText("Despesa");
    mnuNovo.add(mnuIDespesasNovo);

    mnuIOrigemNovo.setText("Origem de Pagamento");
    mnuNovo.add(mnuIOrigemNovo);

    mnuArquivo.add(mnuNovo);

    jMenuBar1.add(mnuArquivo);

    mnuEditar.setText("Editar");

    mnuIDespesasEditar.setText("Despesas");
    mnuEditar.add(mnuIDespesasEditar);

    mnuIOrigemEditar.setText("Origem de Pagamento");
    mnuEditar.add(mnuIOrigemEditar);

    jMenuBar1.add(mnuEditar);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(painelTabelaDespesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
        .addContainerGap(452, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(11, 11, 11)
        .addComponent(painelTabelaDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btAddDespesas;
  public javax.swing.JButton btAtualizaTable;
  public javax.swing.JButton btPagamento;
  public javax.swing.JComboBox cbMes;
  public javax.swing.JComboBox cbOrigenPag;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar jToolBar1;
  public javax.swing.JLabel lbValor;
  private javax.swing.JMenu mnuArquivo;
  public javax.swing.JMenu mnuEditar;
  public javax.swing.JMenuItem mnuIDespesasEditar;
  public javax.swing.JMenuItem mnuIDespesasNovo;
  public javax.swing.JMenuItem mnuIOrigemEditar;
  public javax.swing.JMenuItem mnuIOrigemNovo;
  private javax.swing.JMenu mnuNovo;
  public com.projeto.despesa.form.PainelTabela painelTabelaDespesas;
  public javax.swing.JFormattedTextField tfAno;
  // End of variables declaration//GEN-END:variables
}
